site_name: Cela
site_description: Documentation for Cela.
site_author: myxi
docs_dir: docs/
repo_name: "eeriemyxi/cela"
repo_url: "https://github.com/eeriemyxi/cela"
nav:
    - Getting Started: index.md
    - Custom Parsers: custom-parsers.md
theme:
    name: material
    palette:
        - scheme: slate
          primary: deep purple
          toggle:
              icon: material/brightness-4
              name: Switch to light mode
        - scheme: default
          primary: indigo
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode
extra_css:
    - css/extra.css

markdown_extensions:
    # Python Markdown
    - abbr
    - admonition
    - attr_list
    - def_list
    - footnotes
    - md_in_html
    - toc:
          permalink: true

    # Python Markdown Extensions
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.betterem:
          smart_enable: all
    - pymdownx.caret
    - pymdownx.details
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.tilde
